# Pakistan Tosha Khana Data Wrangling

In [1]:
# Import Libraries
import pandas as pd
import numpy as np 
import seaborn as sns

In [2]:
# load the Data set of Tosha Khana
Tosha_khana = pd.read_csv('Refined_TK_data ver 2.csv')
Tosha_khana

,Detail of Gifts,Item Category,Name of Recipient,Affiliation,Date,Assessed Value,Retention Cost,Retained,Remarks
0,Two small silver\nBowls,Decoration Pieces,"Mr. Abdul Sattar, Minister for Foreign\nA...",Gen. Musharrafarraf,1/8/2002,5000.0,0.0,Yes,Yes
1,One Pilot Pen with\nink,Pen,"Mr. Abdul Sattar, Minister for Foreign\nA...",Gen. Musharraf,1/8/2002,3500.0,0.0,Yes,Yes
2,One silver vase,Decoration Pieces,"Mr. Shaukat Aziz, Minister for Finance",Gen. Musharraf,1/9/2002,7500.0,0.0,Yes,Yes
3,One (decoration)\nfolding Screen,Decoration Pieces,"Mr. Abdul Sattar, Minister for Foreign\nAf...",Gen. Musharraf,1/15/2002,2200.0,0.0,Yes,Yes
4,One Decoration\nPiece,Decoration Pieces,"Mr. Abdul Sattar, Minister for Foreign\nA...",Gen. Musharraf,1/22/2002,2000.0,0.0,Yes,Yes
...,...,...,...,...,...,...,...,...,...
4209,One Model of Door of\nKhana Kaaba,NaN,"Mian Muhammad Shehbaz Sharif,\nPrime Minist...",PMLN,10/18/2022,35000.0,0.0,Displayed\nat Prime\nMinister\nHouse,Displayed\nat Prime\nMinister\nHouse
4210,One Calligraphy duly\nframed,NaN,"SP Mahzoor Ali Ghauri, Chief\nSecurity Off...",NaN,10/20/2022,42000.0,6000.0,Yes,Yes
4211,a. Torsyk Set with\nsilver Tray\nb. Book\nc. ...,NaN,"Mian Muhammad Shehbaz Sharif,\nPrime Minist...",PMLN,10/20/2022,85000.0,0.0,S.No.(a)\ndisplayed at\nPrime\nMinister\nHouse...,S.No.(a)\ndisplayed at\nPrime\nMinister\nHouse...
4212,One Carved wood\npanel,NaN,"Mian Muhammad Shehbaz Sharif,\nPrime Minist...",PMLN,10/20/2022,50000.0,0.0,No,No
4213,a. One Mont Blanc\nBrief Case\nb. One Mont ...,Pen,"Mr. Bilawal Bhutto Zardari,\nMinister for F...",PPP,10/24/2022,434000.0,0.0,No,No

In [3]:
# View the first few rows of the dataset
Tosha_khana.head()

,Detail of Gifts,Item Category,Name of Recipient,Affiliation,Date,Assessed Value,Retention Cost,Retained,Remarks
0,Two small silver\nBowls,Decoration Pieces,"Mr. Abdul Sattar, Minister for Foreign\nA...",Gen. Musharrafarraf,1/8/2002,5000.0,0.0,Yes,Yes
1,One Pilot Pen with\nink,Pen,"Mr. Abdul Sattar, Minister for Foreign\nA...",Gen. Musharraf,1/8/2002,3500.0,0.0,Yes,Yes
2,One silver vase,Decoration Pieces,"Mr. Shaukat Aziz, Minister for Finance",Gen. Musharraf,1/9/2002,7500.0,0.0,Yes,Yes
3,One (decoration)\nfolding Screen,Decoration Pieces,"Mr. Abdul Sattar, Minister for Foreign\nAf...",Gen. Musharraf,1/15/2002,2200.0,0.0,Yes,Yes
4,One Decoration\nPiece,Decoration Pieces,"Mr. Abdul Sattar, Minister for Foreign\nA...",Gen. Musharraf,1/22/2002,2000.0,0.0,Yes,Yes

In [4]:
# View the column names and data types
Tosha_khana.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4214 entries, 0 to 4213
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Detail of Gifts    4208 non-null   object
 1   Item Category      2338 non-null   object
 2   Name of Recipient  4214 non-null   object
 3   Affiliation        3207 non-null   object
 4   Date               4211 non-null   object
 5   Assessed Value     4213 non-null   float64
 6   Retention Cost     4205 non-null   float64
 7   Retained           4203 non-null   object
 8   Remarks            4203 non-null   object
dtypes: float64(2), object(7)
memory usage: 296.4+ KB

In [5]:
# Check for missing values
print(Tosha_khana.isnull().sum())

Detail of Gifts         6
Item Category        1876
Name of Recipient       0
Affiliation          1007
Date                    3
Assessed Value          1
Retention Cost          9
Retained               11
Remarks                11
dtype: int64

In [6]:
# Handle missing values
# Option 1: Drop rows with missing values
Tosha_khana.dropna(inplace=True)

In [7]:
print(Tosha_khana.isnull().sum())

Detail of Gifts      0
Item Category        0
Name of Recipient    0
Affiliation          0
Date                 0
Assessed Value       0
Retention Cost       0
Retained             0
Remarks              0
dtype: int64

In [8]:
Tosha_khana

,Detail of Gifts,Item Category,Name of Recipient,Affiliation,Date,Assessed Value,Retention Cost,Retained,Remarks
0,Two small silver\nBowls,Decoration Pieces,"Mr. Abdul Sattar, Minister for Foreign\nA...",Gen. Musharrafarraf,1/8/2002,5000.0,0.0,Yes,Yes
1,One Pilot Pen with\nink,Pen,"Mr. Abdul Sattar, Minister for Foreign\nA...",Gen. Musharraf,1/8/2002,3500.0,0.0,Yes,Yes
2,One silver vase,Decoration Pieces,"Mr. Shaukat Aziz, Minister for Finance",Gen. Musharraf,1/9/2002,7500.0,0.0,Yes,Yes
3,One (decoration)\nfolding Screen,Decoration Pieces,"Mr. Abdul Sattar, Minister for Foreign\nAf...",Gen. Musharraf,1/15/2002,2200.0,0.0,Yes,Yes
4,One Decoration\nPiece,Decoration Pieces,"Mr. Abdul Sattar, Minister for Foreign\nA...",Gen. Musharraf,1/22/2002,2000.0,0.0,Yes,Yes
...,...,...,...,...,...,...,...,...,...
4195,Tea set (16 pcs),Crockery,"Mian Muhammad Shehbaz Sharif,\nPrime Minist...",PMLN,9/29/2022,70000.0,0.0,No,No
4198,a. 24k gold plated\nstand.\nb. 24k gold pre...,Carpet,"Mian Muhammad Shehbaz Sharif,\nPrime Minist...",PMLN,9/29/2022,562400.0,0.0,"Sr.No.(a,b,f\n) displayed\nat Prime\nMinister\...","Sr.No.(a,b,f\n) displayed\nat Prime\nMinister\..."
4203,24k Silver/Gold plated\nvase,Decoration Pieces,"Mian Muhammad Shehbaz Sharif,\nPrime Minist...",PMLN,9/29/2022,400000.0,185000.0,Displayed\nat Prime\nMinister\nHouse,Displayed\nat Prime\nMinister\nHouse
4207,Tea set (5 pieces),Crockery,"Mr. Bilawal Bhutto Zardari,\nMinister for F...",PPP,10/12/2022,285000.0,0.0,No,No
4213,a. One Mont Blanc\nBrief Case\nb. One Mont ...,Pen,"Mr. Bilawal Bhutto Zardari,\nMinister for F...",PPP,10/24/2022,434000.0,0.0,No,No

In [9]:
#load the again data set of tosha khana after checking the Missing Values
# load the Data set of Tosha Khana
Tosha_khana_1 = pd.read_csv('Refined_TK_data ver 2.csv')
Tosha_khana_1

,Detail of Gifts,Item Category,Name of Recipient,Affiliation,Date,Assessed Value,Retention Cost,Retained,Remarks
0,Two small silver\nBowls,Decoration Pieces,"Mr. Abdul Sattar, Minister for Foreign\nA...",Gen. Musharrafarraf,1/8/2002,5000.0,0.0,Yes,Yes
1,One Pilot Pen with\nink,Pen,"Mr. Abdul Sattar, Minister for Foreign\nA...",Gen. Musharraf,1/8/2002,3500.0,0.0,Yes,Yes
2,One silver vase,Decoration Pieces,"Mr. Shaukat Aziz, Minister for Finance",Gen. Musharraf,1/9/2002,7500.0,0.0,Yes,Yes
3,One (decoration)\nfolding Screen,Decoration Pieces,"Mr. Abdul Sattar, Minister for Foreign\nAf...",Gen. Musharraf,1/15/2002,2200.0,0.0,Yes,Yes
4,One Decoration\nPiece,Decoration Pieces,"Mr. Abdul Sattar, Minister for Foreign\nA...",Gen. Musharraf,1/22/2002,2000.0,0.0,Yes,Yes
...,...,...,...,...,...,...,...,...,...
4209,One Model of Door of\nKhana Kaaba,NaN,"Mian Muhammad Shehbaz Sharif,\nPrime Minist...",PMLN,10/18/2022,35000.0,0.0,Displayed\nat Prime\nMinister\nHouse,Displayed\nat Prime\nMinister\nHouse
4210,One Calligraphy duly\nframed,NaN,"SP Mahzoor Ali Ghauri, Chief\nSecurity Off...",NaN,10/20/2022,42000.0,6000.0,Yes,Yes
4211,a. Torsyk Set with\nsilver Tray\nb. Book\nc. ...,NaN,"Mian Muhammad Shehbaz Sharif,\nPrime Minist...",PMLN,10/20/2022,85000.0,0.0,S.No.(a)\ndisplayed at\nPrime\nMinister\nHouse...,S.No.(a)\ndisplayed at\nPrime\nMinister\nHouse...
4212,One Carved wood\npanel,NaN,"Mian Muhammad Shehbaz Sharif,\nPrime Minist...",PMLN,10/20/2022,50000.0,0.0,No,No
4213,a. One Mont Blanc\nBrief Case\nb. One Mont ...,Pen,"Mr. Bilawal Bhutto Zardari,\nMinister for F...",PPP,10/24/2022,434000.0,0.0,No,No

In [10]:
# rename columns
df=Tosha_khana_1.rename(columns = {'Detail of Gifts': 'Gift_detail','Item Category': 'Item_category','Name of Recipient': 'Recipient_name','Assessed Value': 'Assessed_value','Retention Cost': 'Retention_cost'})
df

,Gift_detail,Item_category,Recipient_name,Affiliation,Date,Assessed_value,Retention_cost,Retained,Remarks
0,Two small silver\nBowls,Decoration Pieces,"Mr. Abdul Sattar, Minister for Foreign\nA...",Gen. Musharrafarraf,1/8/2002,5000.0,0.0,Yes,Yes
1,One Pilot Pen with\nink,Pen,"Mr. Abdul Sattar, Minister for Foreign\nA...",Gen. Musharraf,1/8/2002,3500.0,0.0,Yes,Yes
2,One silver vase,Decoration Pieces,"Mr. Shaukat Aziz, Minister for Finance",Gen. Musharraf,1/9/2002,7500.0,0.0,Yes,Yes
3,One (decoration)\nfolding Screen,Decoration Pieces,"Mr. Abdul Sattar, Minister for Foreign\nAf...",Gen. Musharraf,1/15/2002,2200.0,0.0,Yes,Yes
4,One Decoration\nPiece,Decoration Pieces,"Mr. Abdul Sattar, Minister for Foreign\nA...",Gen. Musharraf,1/22/2002,2000.0,0.0,Yes,Yes
...,...,...,...,...,...,...,...,...,...
4209,One Model of Door of\nKhana Kaaba,NaN,"Mian Muhammad Shehbaz Sharif,\nPrime Minist...",PMLN,10/18/2022,35000.0,0.0,Displayed\nat Prime\nMinister\nHouse,Displayed\nat Prime\nMinister\nHouse
4210,One Calligraphy duly\nframed,NaN,"SP Mahzoor Ali Ghauri, Chief\nSecurity Off...",NaN,10/20/2022,42000.0,6000.0,Yes,Yes
4211,a. Torsyk Set with\nsilver Tray\nb. Book\nc. ...,NaN,"Mian Muhammad Shehbaz Sharif,\nPrime Minist...",PMLN,10/20/2022,85000.0,0.0,S.No.(a)\ndisplayed at\nPrime\nMinister\nHouse...,S.No.(a)\ndisplayed at\nPrime\nMinister\nHouse...
4212,One Carved wood\npanel,NaN,"Mian Muhammad Shehbaz Sharif,\nPrime Minist...",PMLN,10/20/2022,50000.0,0.0,No,No
4213,a. One Mont Blanc\nBrief Case\nb. One Mont ...,Pen,"Mr. Bilawal Bhutto Zardari,\nMinister for F...",PPP,10/24/2022,434000.0,0.0,No,No

In [11]:
df.isnull().count()

Gift_detail       4214
Item_category     4214
Recipient_name    4214
Affiliation       4214
Date              4214
Assessed_value    4214
Retention_cost    4214
Retained          4214
Remarks           4214
dtype: int64

In [12]:
# View the column names and data types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4214 entries, 0 to 4213
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Gift_detail     4208 non-null   object
 1   Item_category   2338 non-null   object
 2   Recipient_name  4214 non-null   object
 3   Affiliation     3207 non-null   object
 4   Date            4211 non-null   object
 5   Assessed_value  4213 non-null   float64
 6   Retention_cost  4205 non-null   float64
 7   Retained        4203 non-null   object
 8   Remarks         4203 non-null   object
dtypes: float64(2), object(7)
memory usage: 296.4+ KB

In [13]:
df.isnull().sum()*100/ len(df)

Gift_detail        0.142383
Item_category     44.518272
Recipient_name     0.000000
Affiliation       23.896535
Date               0.071191
Assessed_value     0.023730
Retention_cost     0.213574
Retained           0.261035
Remarks            0.261035
dtype: float64

In [14]:
# Check for missing values
print(df.isnull().sum())

Gift_detail          6
Item_category     1876
Recipient_name       0
Affiliation       1007
Date                 3
Assessed_value       1
Retention_cost       9
Retained            11
Remarks             11
dtype: int64

In [15]:
# Handle missing values
df.dropna(inplace=True)

In [16]:
df.isnull().sum()*100/len(df)

Gift_detail       0.0
Item_category     0.0
Recipient_name    0.0
Affiliation       0.0
Date              0.0
Assessed_value    0.0
Retention_cost    0.0
Retained          0.0
Remarks           0.0
dtype: float64

In [17]:
df.isnull().sum()

Gift_detail       0
Item_category     0
Recipient_name    0
Affiliation       0
Date              0
Assessed_value    0
Retention_cost    0
Retained          0
Remarks           0
dtype: int64

In [29]:
# removing unncessary strings from Gift_detail
df['Gift_detail'] = df['Gift_detail'].str.replace('\n', ' ')
df['Gift_detail']

0                                 Two  small  silverBowls
1                                   One Pilot Pen withink
2                                         One silver vase
3                         One  (decoration)folding Screen
4                                    One  DecorationPiece
                              ...
4195                                     Tea set (16 pcs)
4198    a. 24k gold  platedstand.b. 24k  gold  premium...
4203                           24k Silver/Gold platedvase
4207                                   Tea set (5 pieces)
4213    a. One  Mont  BlancBrief Caseb. One  Mont  Bla...
Name: Gift_detail, Length: 1812, dtype: object

In [30]:
df['Gift_detail'].value_counts()

One Carpet                                                                          42
One carpet                                                                          31
Wrist  Watch(Concord)                                                               20
One  wrist  watchOfficina Del Tempo                                                 19
Wrist watch Rolex                                                                   15
                                                                                    ..
Two  decoration  piecesin silver                                                     1
A  camera  Olympus(170S)                                                             1
a. One Flower vaseb. One  decorationshield (Plate)                                   1
One Decoration shield                                                                1
a. One  Mont  BlancBrief Caseb. One  Mont  BlancPen.c. One  Mont  BlancNote Book     1
Name: Gift_detail, Length: 1324, dtype: int64

In [32]:
df

,Gift_detail,Item_category,Recipient_name,Affiliation,Date,Assessed_value,Retention_cost,Retained,Remarks
0,Two small silverBowls,Decoration Pieces,"Mr. Abdul Sattar, Minister for Foreign Af...",Gen. Musharrafarraf,1/8/2002,5000.0,0.0,Yes,Yes
1,One Pilot Pen withink,Pen,"Mr. Abdul Sattar, Minister for Foreign Af...",Gen. Musharraf,1/8/2002,3500.0,0.0,Yes,Yes
2,One silver vase,Decoration Pieces,"Mr. Shaukat Aziz, Minister for Finance",Gen. Musharraf,1/9/2002,7500.0,0.0,Yes,Yes
3,One (decoration)folding Screen,Decoration Pieces,"Mr. Abdul Sattar, Minister for Foreign Aff...",Gen. Musharraf,1/15/2002,2200.0,0.0,Yes,Yes
4,One DecorationPiece,Decoration Pieces,"Mr. Abdul Sattar, Minister for Foreign Af...",Gen. Musharraf,1/22/2002,2000.0,0.0,Yes,Yes
...,...,...,...,...,...,...,...,...,...
4195,Tea set (16 pcs),Crockery,"Mian Muhammad Shehbaz Sharif, Prime Ministe...",PMLN,9/29/2022,70000.0,0.0,No,No
4198,a. 24k gold platedstand.b. 24k gold premium...,Carpet,"Mian Muhammad Shehbaz Sharif, Prime Ministe...",PMLN,9/29/2022,562400.0,0.0,"Sr.No.(a,b,f\n) displayed\nat Prime\nMinister\...","Sr.No.(a,b,f\n) displayed\nat Prime\nMinister\..."
4203,24k Silver/Gold platedvase,Decoration Pieces,"Mian Muhammad Shehbaz Sharif, Prime Ministe...",PMLN,9/29/2022,400000.0,185000.0,Displayed\nat Prime\nMinister\nHouse,Displayed\nat Prime\nMinister\nHouse
4207,Tea set (5 pieces),Crockery,"Mr. Bilawal Bhutto Zardari, Minister for Fo...",PPP,10/12/2022,285000.0,0.0,No,No
4213,a. One Mont BlancBrief Caseb. One Mont Bla...,Pen,"Mr. Bilawal Bhutto Zardari, Minister for Fo...",PPP,10/24/2022,434000.0,0.0,No,No

In [27]:
df['Recipient_name'] = df['Recipient_name'].str.replace('\n', ' ')
df['Recipient_name']

0       Mr.  Abdul  Sattar,  Minister  for  Foreign Af...
1       Mr.  Abdul  Sattar,  Minister  for  Foreign Af...
2                  Mr. Shaukat Aziz, Minister for Finance
3       Mr.  Abdul Sattar,  Minister  for  Foreign Aff...
4       Mr.  Abdul  Sattar,  Minister  for  Foreign Af...
                              ...
4195    Mian  Muhammad  Shehbaz  Sharif, Prime Ministe...
4198    Mian  Muhammad  Shehbaz  Sharif, Prime Ministe...
4203    Mian  Muhammad  Shehbaz  Sharif, Prime Ministe...
4207    Mr.  Bilawal  Bhutto  Zardari, Minister for Fo...
4213    Mr.  Bilawal  Bhutto  Zardari, Minister for Fo...
Name: Recipient_name, Length: 1812, dtype: object

In [28]:
df

,Gift_detail,Item_category,Recipient_name,Affiliation,Date,Assessed_value,Retention_cost,Retained,Remarks
0,Two small silverBowls,Decoration Pieces,"Mr. Abdul Sattar, Minister for Foreign Af...",Gen. Musharrafarraf,1/8/2002,5000.0,0.0,Yes,Yes
1,One Pilot Pen withink,Pen,"Mr. Abdul Sattar, Minister for Foreign Af...",Gen. Musharraf,1/8/2002,3500.0,0.0,Yes,Yes
2,One silver vase,Decoration Pieces,"Mr. Shaukat Aziz, Minister for Finance",Gen. Musharraf,1/9/2002,7500.0,0.0,Yes,Yes
3,One (decoration)folding Screen,Decoration Pieces,"Mr. Abdul Sattar, Minister for Foreign Aff...",Gen. Musharraf,1/15/2002,2200.0,0.0,Yes,Yes
4,One DecorationPiece,Decoration Pieces,"Mr. Abdul Sattar, Minister for Foreign Af...",Gen. Musharraf,1/22/2002,2000.0,0.0,Yes,Yes
...,...,...,...,...,...,...,...,...,...
4195,Tea set (16 pcs),Crockery,"Mian Muhammad Shehbaz Sharif, Prime Ministe...",PMLN,9/29/2022,70000.0,0.0,No,No
4198,a. 24k gold platedstand.b. 24k gold premium...,Carpet,"Mian Muhammad Shehbaz Sharif, Prime Ministe...",PMLN,9/29/2022,562400.0,0.0,"Sr.No.(a,b,f\n) displayed\nat Prime\nMinister\...","Sr.No.(a,b,f\n) displayed\nat Prime\nMinister\..."
4203,24k Silver/Gold platedvase,Decoration Pieces,"Mian Muhammad Shehbaz Sharif, Prime Ministe...",PMLN,9/29/2022,400000.0,185000.0,Displayed\nat Prime\nMinister\nHouse,Displayed\nat Prime\nMinister\nHouse
4207,Tea set (5 pieces),Crockery,"Mr. Bilawal Bhutto Zardari, Minister for Fo...",PPP,10/12/2022,285000.0,0.0,No,No
4213,a. One Mont BlancBrief Caseb. One Mont Bla...,Pen,"Mr. Bilawal Bhutto Zardari, Minister for Fo...",PPP,10/24/2022,434000.0,0.0,No,No

In [37]:
df['Retained'] =df['Retained'].str.replace('\n', ' ')

In [38]:
df['Retained']

0                                                     Yes
1                                                     Yes
2                                                     Yes
3                                                     Yes
4                                                     Yes
                              ...
4195                                                   No
4198    Sr.No.(a,b,f ) displayed at Prime Minister Hou...
4203                    Displayed at Prime Minister House
4207                                                   No
4213                                                   No
Name: Retained, Length: 1812, dtype: object

In [39]:
df['Remarks'] = df['Remarks'].str.replace('\n', ' ')
df['Remarks']

0                                                     Yes
1                                                     Yes
2                                                     Yes
3                                                     Yes
4                                                     Yes
                              ...
4195                                                   No
4198    Sr.No.(a,b,f ) displayed at Prime Minister Hou...
4203                    Displayed at Prime Minister House
4207                                                   No
4213                                                   No
Name: Remarks, Length: 1812, dtype: object

In [40]:
df['Item_category'].value_counts()

Watch                         835
Decoration Pieces             434
Carpet                        188
Pen                            92
Crockery                       89
Jewellery/Accessories          48
Cigar/Cigarettes               27
Clothes                        23
Weapons                        21
Phone                          21
Food                           10
Bags                            9
Tech                            8
Watch, Weapons                  2
Watch, phone                    1
Technology                      1
Jewellery, Weapons              1
Bag, Jewellery/Accessories      1
Tech, pen                       1
Name: Item_category, dtype: int64

In [41]:
# change datatype of date colmn
df['Date'] = pd.to_datetime(df['Date'])
df['Date']

0      2002-01-08
1      2002-01-08
2      2002-01-09
3      2002-01-15
4      2002-01-22
          ...
4195   2022-09-29
4198   2022-09-29
4203   2022-09-29
4207   2022-10-12
4213   2022-10-24
Name: Date, Length: 1812, dtype: datetime64[ns]

In [42]:
print(df.isnull().sum())

Gift_detail       0
Item_category     0
Recipient_name    0
Affiliation       0
Date              0
Assessed_value    0
Retention_cost    0
Retained          0
Remarks           0
dtype: int64

In [43]:
df

,Gift_detail,Item_category,Recipient_name,Affiliation,Date,Assessed_value,Retention_cost,Retained,Remarks
0,Two small silverBowls,Decoration Pieces,"Mr. Abdul Sattar, Minister for Foreign Af...",Gen. Musharrafarraf,2002-01-08,5000.0,0.0,Yes,Yes
1,One Pilot Pen withink,Pen,"Mr. Abdul Sattar, Minister for Foreign Af...",Gen. Musharraf,2002-01-08,3500.0,0.0,Yes,Yes
2,One silver vase,Decoration Pieces,"Mr. Shaukat Aziz, Minister for Finance",Gen. Musharraf,2002-01-09,7500.0,0.0,Yes,Yes
3,One (decoration)folding Screen,Decoration Pieces,"Mr. Abdul Sattar, Minister for Foreign Aff...",Gen. Musharraf,2002-01-15,2200.0,0.0,Yes,Yes
4,One DecorationPiece,Decoration Pieces,"Mr. Abdul Sattar, Minister for Foreign Af...",Gen. Musharraf,2002-01-22,2000.0,0.0,Yes,Yes
...,...,...,...,...,...,...,...,...,...
4195,Tea set (16 pcs),Crockery,"Mian Muhammad Shehbaz Sharif, Prime Ministe...",PMLN,2022-09-29,70000.0,0.0,No,No
4198,a. 24k gold platedstand.b. 24k gold premium...,Carpet,"Mian Muhammad Shehbaz Sharif, Prime Ministe...",PMLN,2022-09-29,562400.0,0.0,"Sr.No.(a,b,f ) displayed at Prime Minister Hou...","Sr.No.(a,b,f ) displayed at Prime Minister Hou..."
4203,24k Silver/Gold platedvase,Decoration Pieces,"Mian Muhammad Shehbaz Sharif, Prime Ministe...",PMLN,2022-09-29,400000.0,185000.0,Displayed at Prime Minister House,Displayed at Prime Minister House
4207,Tea set (5 pieces),Crockery,"Mr. Bilawal Bhutto Zardari, Minister for Fo...",PPP,2022-10-12,285000.0,0.0,No,No
4213,a. One Mont BlancBrief Caseb. One Mont Bla...,Pen,"Mr. Bilawal Bhutto Zardari, Minister for Fo...",PPP,2022-10-24,434000.0,0.0,No,No

In [44]:
df.shape

(1812, 9)